[tox]
requires =
    tox>=4.55
    tox-uv>=1.35.2
env_list = py3{10-}, deps

[testenv]
description = run tests on Python {py_dot_ver}
runner = uv-venv-lock-runner
dependency_groups =
  dev
commands =
  pytest {posargs:tests}

[testenv:deps]
description = check for unused, missing and transitive dependencies
dependency_groups =
  dev
commands =
  deptry {posargs:tap_dbt}
