name: TestPyPI

on:
  push:
    branches:
      - main

jobs:
  test_pypi:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: x64

      - name: Install Dependencies
        run: pip install poetry==1.1.5

      - name: Bump version
        run: |
          poetry version patch
          version=$(poetry version | awk '{print $2}')
          poetry version $version.dev.$(date +%s)

      - name: Build
        run: poetry build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
